# Custom Language File for Launcher Customizer

[ejs.app]
title = "Cookie Launcher"

[ejs.landing]
mediaLinkURL = "https://cosmicstudio.space"
mediaGitHubURL = "https://github.com/mxxndawn/CookieLauncher"
mediaMapURL = "https://map.cosmicstudio.space"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/hGAAwGwwwH"

[ejs.settings]
sourceGithubLink = "https://github.com/mxxndawn/CookieLauncher"
supportLink = "https://github.com/mxxndawn/CookieLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO CookieServer"
welcomeDescription = "2011년, 초록창 카페의 작은 서버로 시작한 Cookie Server는 잠시나마 유저들에게 즐거움과 편안함을 느낄 수 있는 소중한 보금자리였습니다. 다시 시작하는 Cookie Server는 단순한 마인크래프트를 넘어서, 더 재미있는 콘텐츠를 즐길 수 있고 수많은 사람들과 교류할 수 있는 커뮤니티의 한 장소가 되고자 합니다."
welcomeDescCTA = "쿠키서버와 함께 즐거운 시간 되시길 바랍니다."
